---
- hosts: all
  become: yes

  tasks:
    - name: Update apt cache and perform a safe upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      notify: Check for reboot

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Remove unnecessary dependencies and purge their configuration files
      ansible.builtin.apt:
        autoremove: yes
        purge: yes

    - name: Clean up apt cache
      ansible.builtin.apt:
        clean: yes

  handlers:
    - name: Check for reboot
      ansible.builtin.debug:
        msg: "Checking if reboot is required..."
      when: reboot_required_file.stat.exists == true
      notify: Reboot server

    - name: Reboot server
      ansible.builtin.reboot:
        msg: "System needs to reboot to apply updates."
        pre_reboot_delay: 60
      when: reboot_required_file.stat.exists == true
